### ISSUE TITLE
update opencv to 4.0

### ISSUE THREAD

**Issue by zcaudate** [hellonico/origami#10]
opencv 4.0 is out and it would be great if the library was updated to support this version

**Comment by hellonico** [comment]
For sure. 
Are you looking into a specific new function ? 
Also which plateform linux/windows/osx/arm are you looking to use first ?

**Comment by zcaudate** [comment]
I'm on a mac and also use ubuntu. There wasn't a specific function. There's just quite a lot of patches that's gone in between the beta and the final release.

**Comment by zcaudate** [comment]
thanks. I really appreciate it

**Comment by hellonico** [comment]
4.0.0 natives are in:
https://github.com/hellonico/opencv4-native/tree/master/natives

Included natives are:
- arm64
- linux64
- win64
- osx64

Uploaded here:
http://repository.hellonico.info/#browse/browse:hellonico:opencv%2Fopencv%2F4.0.0-0
http://repository.hellonico.info/#browse/browse:hellonico:opencv%2Fopencv-native%2F4.0.0-0

Released a new origami version
https://github.com/hellonico/origami/commit/8dcd1ea34811273b3db5344295254a93425cae3a
http://repository.hellonico.info/#browse/browse:hellonico:origami%2Forigami%2F4.0.0-0

Tested with:
```
opencv4.ok=> (require '[opencv4.core])
opencv4.ok=> (println VERSION)
4.0.0
```

Related projects have been updated:
https://github.com/hellonico/origami_samples 
https://github.com/hellonico/opencv-fun
https://github.com/hellonico/origami-dnn

And new project templates are in:
https://clojars.org/jvm-opencv/lein-template (java only)
https://clojars.org/clj-opencv/lein-template (clojure)

**Comment by zcaudate** [comment]
ah amazing.
