### ISSUE TITLE
how is the opencv artifact being built?

### ISSUE THREAD

**Issue by zcaudate** [hellonico/origami#11]
I'd like to be able to reproduce both the opencv-native and opencv artifacts if possible.

**Comment by hellonico** [comment]
The repository and code is here: 
https://github.com/hellonico/opencv4-native

**Comment by zcaudate** [comment]
Ah awesome. Do you build each of the native libs with Virtual Box?

**Comment by zcaudate** [comment]
would it be possible to use travis to build and then upload to aws/ftp?
 
https://blog.travis-ci.com/2018-10-11-windows-early-release 

that just leaves the arm build

**Comment by zcaudate** [comment]
http://answers.opencv.org/question/21977/best-way-to-depend-on-opencv-master-in-a-travis-ci-build-bot-instance/

**Comment by hellonico** [comment]
Totally agree!  but no plan to do it in the short term.
