### ISSUE TITLE
Refactoring

### ISSUE THREAD

**Issue by hellonico** [hellonico/origami#14]
- [x] Move Gorilla code in its own namespace
- [x] remove gorilla direct dependency in origami-core
   - [x] In gorilla code, use mat directly instead of using a buffered image (may need to reverse channels)
   - [x] in origami-fun, update all call to utils/mat-view to g/->view
   - [x] fix blank image in notebook
   - [x] update template
   - [x] update samples project
- [x] Improve integration with clojupyter

**Comment by Dwaynekj** [comment]
@hellonico Hey is this project still active?

**Comment by hellonico** [comment]
yup. looking for something ?

**Comment by Dwaynekj** [comment]
I'll open a different ticket so as not to pollute this thread

**Comment by hellonico** [comment]
all this released in:

4.0.0-6
