### ISSUE TITLE
`cvu/buffered-image-to-mat` fails for some bufferedImages

### ISSUE THREAD

**Issue by Chouffe** [hellonico/origami#17]
I am trying to use the `cvu/buffered-image-to-mat` with a RGB image like so:
```
(require '[opencv4.utils :as cvu])
(require '[org.apache.clojure-mxnet.image :as mx-img])

(-> "images/dog.jpg"
       (mx-img/read-image {:to-rgb true}) ;; NDArray a this point
       mx-img/to-image ;; BufferedImage at this point
       cvu/buffered-image-to-mat ;; Fails to convert to `Mat`...
        )
```
It fails with the following error message:
```
Syntax error (UnsupportedOperationException) compiling at (:112:5).
Mat data type is not compatible: 16
```
I suspect it comes from the `BufferedImage` type that does not match the `Mat` type.
From what I gathered on StackOverflow some people need to either cast the `(.getDataBuffer)` to a `DataBufferByte` or change the `BufferedImage`.

**Comment by hellonico** [comment]
The retrieved bufferedimage from
```
mx-img/to-image
``` 
converts the mxnet image to a BufferedImage of underlying type Integer, which are 32 bits in Java.

I have added some code in origami/utils.clj to make sure the buffered image is of expected type:
https://github.com/hellonico/origami/commit/03b287b118e7a9bc612bca4f6d6813e3980b552d

Then the conversion to an opencv image works well.

Let me know if that works for you, and I'll cut a new release.

**Comment by hellonico** [comment]
Actually released a version:

```
[origami "4.0.0-4"]
```

**Comment by hellonico** [comment]
resolved
