### ISSUE TITLE
opencv4.utils/cams-windows malfunction

### ISSUE THREAD

**Issue by DuncanChang** [hellonico/origami#22]
I traced the code. Looks like the problem is in opencv4.utils/start-cam-thread:
(line 360)
`(.open (str (-> device-map :device)))`

why stringify the device id here?
maybe it should be:
`(.open (-> device-map :device))`

**Comment by hellonico** [comment]
nice catch ! 
committed and released  4.0.0-8

**Comment by DuncanChang** [comment]
4.0.0-8 works fine. Good job.
