### ISSUE TITLE
opencv4.core contains two implementation of copy-to/copy-to! function

### ISSUE THREAD

**Issue by DuncanChang** [hellonico/origami#25]
line 78~82
```
(defn copy-to
  ([src target] (.copyTo src target))
  ([src target mask] (.copyTo src target mask)))

(defn copy-to![src mask]
  (copy-to src src mask))
```

These are wrappers for org.opencv.core.Mat.copyTo method.

line 2489~2497
```
(defn copy-to
([org_opencv_core_mat_0 org_opencv_core_mat_1 org_opencv_core_mat_2 ] 
  (Core/copyTo org_opencv_core_mat_0 org_opencv_core_mat_1 org_opencv_core_mat_2 ))
)

(defn copy-to!
([org_opencv_core_mat_0 org_opencv_core_mat_2 ] 
  (Core/copyTo org_opencv_core_mat_0 org_opencv_core_mat_0 org_opencv_core_mat_2 ) org_opencv_core_mat_0 )
)
```
These are wrappers for org.opencv.core.Core.copyTo static method.

Currently the later version overwrite the former one, so we must provide mask mat argument.
It is a bit annoying.

Maybe drop the later implementation?

**Comment by hellonico** [comment]
nicely spotted !
Let me do it now.

**Comment by hellonico** [comment]
It's in! 4.0.0-10

**Comment by hellonico** [comment]
let me know if it solved your problem, and if you have an example to share !

**Comment by DuncanChang** [comment]
Yeah, copy-to is 2~3 arity in 4.0.0-10.

**Comment by hellonico** [comment]
Thanks for testing !
