### ISSUE TITLE
OpenCV 4.3

### ISSUE THREAD

**Issue by sunng87** [hellonico/origami#34]
OpenCV 4.3 just released. It will be nice to update.

**Comment by hellonico** [comment]
Started working on it !

**Comment by hellonico** [comment]
released !

**Comment by hellonico** [comment]
Can you test it ?

```
lein new clj-opencv hellocv
cd hellocv
lein run
```

**Comment by sunng87** [comment]
Thank you for fast response. The new version works for me.
