### ISSUE TITLE
V4L and the video/webcam example on Linux

### ISSUE THREAD

**Issue by geokon-gh** [hellonico/origami#5]
btw, did you get the video example working on your Debian VM?
I get a blank white box for your example:

```
(u/simple-cam-window
 (fn [buffer]
     (u/resize-by buffer 0.5)
     (let [ output (new-mat) bottom (-> buffer clone (flip! -1)) ]
       (-> buffer (cvt-color! COLOR_RGB2GRAY) (cvt-color! COLOR_GRAY2RGB))
       (put-text buffer (str (java.util.Date.)) (new-point 10 50) FONT_HERSHEY_PLAIN 1 (new-scalar 255 255 0) 1)
       (vconcat [buffer bottom] output)
       output)))
```

I tried to change the device number as well by passing in 
`{:frame {:color "00" :title "video" :width 400 :height 400} :video {:device 1 :width 200 :height 220}}` but without any luck. 

The likely issue is V4L ([it's a necessary dependency for video in OpenCV](https://docs.opencv.org/3.2.0/d0/da7/videoio_overview.html), CMake's WITH_LIBV4L flag is OFF by default, it isn't something installed by OpenCV and it's not installed on the system by default). 

I went to 
`~/.m2/repository/opencv/opencv-native/3.3.1_4/opencv-native-3.3.1_4.jar`
Then I extracted the `native/x86_64/libopencv_java331.so` in to a temporary directory and ran `ldd` on it and got the following

```
$ldd libopencv_java331.so 
        linux-vdso.so.1 (0x00007fff781e8000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fdb1cd2b000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fdb1cb27000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fdb1c909000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fdb1c701000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fdb1c3b6000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fdb1c19e000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fdb1bde8000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fdb21818000)
```
Then I took OpenCV and built it through CMake (I'm at v3.2 and I disabled almost everything not video or java related) and I get the following:

```
$ldd libopencv_java330.so 
        linux-vdso.so.1 (0x00007ffe981ee000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f502615e000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f5025f5a000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f5025d3c000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f5025b34000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f502591a000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f50255cf000)
        libv4l1.so.0 => /usr/lib/x86_64-linux-gnu/libv4l1.so.0 (0x00007f50253c9000)
        libv4l2.so.0 => /usr/lib/x86_64-linux-gnu/libv4l2.so.0 (0x00007f50251ba000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f5024fa2000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f5024bec000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f5026d78000)
        libv4lconvert.so.0 => /usr/lib/x86_64-linux-gnu/libv4lconvert.so.0 (0x00007f5024972000)
        libjpeg.so.62 => /usr/lib/x86_64-linux-gnu/libjpeg.so.62 (0x00007f5024709000)

```

Another potential issue is that Debian stretch/stable is at v1.12 and Debian stretch is at v1.14... but maybe it's okay

**Comment by hellonico** [comment]
My debian only has the bare minimum server stuff. So no GUI whatsoever. 
It did work on Manjaro before, but that was before I recompiled the lib with new flags this week ;) 
And so, looking at the flag I used shows that I did not set the V4L flag.

Could you send me the ISO file you used to bootstrap your debian ? 
I'll then setup one similar to yours. There is no reason the video should not play.

**Comment by geokon-gh** [comment]
Great! That did it. It's working here as well :)

**Comment by hellonico** [comment]
party !

**Comment by geokon-gh** [comment]
:))
