### ISSUE TITLE
Getting "Could not transfer artifact..." error from https://repository.hellonico.info/repository/hellonico/

### ISSUE THREAD

**Issue by countgizmo** [hellonico/origami#58]
First of all, thank you for all the hard work on origami - great project, really appreciate it!

We're using origami in our project for awhile now without any issues, but today I've had to reinstall project's clojure dependencies from scratch and came across this error:

```
Error building classpath. Could not transfer artifact opencv:opencv-native:jar:4.2.0-0 from/to vendredi (https://repository.hellonico.info/repository/hellonico/): Premature end of Content-Length delimited message body (expected: 77571263; received: 130548
```
It looks like the server cuts the connection early but I have no clue why.
All the other dependencies from other repositories were downloaded without any issues.

P.S. I've also tried the latest version of origami with the same result.

**Comment by hellonico** [comment]
hi ! thank you for the report ! 

what's your project setup ?

**Comment by countgizmo** [comment]
It's based on deps.edn with origami related stuff specified as;

```
{:mvn/repos
  {...
  "central"    {:url "https://repo1.maven.org/maven2/"}
  "vendredi"   {:url "https://repository.hellonico.info/repository/hellonico/"}}
  {
   :deps
    {...
     origami/origami                       {:mvn/version "4.2.0-7"}
    }
...
```

**Comment by hellonico** [comment]
Thanks ! Will have a look within the next 2 hours and get back to you asap.

**Comment by hellonico** [comment]
Hi Again,
My nexus repository crashed :/  
I really wish I could upload the artefacts to clojars but the native jar is too big for them :/ 

Anyway, I did the recovery and you should be able to get back on tracks.
Clojure CLI worked for me with:

```
{:mvn/repos
 {"vendredi" {:url "https://repository.hellonico.info/repository/hellonico/"}}
 :deps
 {origami {:mvn/version "4.3.0-7"}
}}
```

PS: Would love to have a quick demo on how you are using origami ;)

**Comment by countgizmo** [comment]
@hellonico thanks for the quick response (we are restarting our builds now).
And I would love to do a quick demo I just need to get an approval from the management :)

**Comment by hellonico** [comment]
Hope your builds are fine. 
Looking forward to the demo !

**Comment by narendraj9** [comment]
@hellonico The Maven repository is down again. Please take a look.
