### ISSUE TITLE
Getting pixel values

### ISSUE THREAD

**Issue by geokon-gh** [hellonico/origami#6]
I was trying to do something rather simple and go over my black and white image pixel by pixel and build up a histogram. I might be doing something wrong but I can't seem to get the pixel values out into Clojure. I've never used OpenCV through Java (just C++) so I'm likely missing some finer point.

I've stripped down my problem to the bare minimum. I want to just fetch one pixel value from a image taken from my webcam. I have a simple function that grabs that one image and returns it as a opencv matrix (I also tried to do it using your `mat-to-buffered-image` and Java's BufferedImage but I got stuck there as well)

```

(defn webcam-bufferedimage-still
  ""
  []
  (let [webcam-options {:frame {:color "00" :title "video"} :video {:device 0 :width 320 :height 240 :datatype oc/CV_8UC3 }}
        webcam-capture (ov/new-videocapture)
        webcam-buffer (oc/new-mat)]

    (doto webcam-capture
      (.open (int (-> webcam-options :video :device)))
      (.set ov/CAP_PROP_FRAME_WIDTH (-> webcam-options :video :width))
      (.set ov/CAP_PROP_FRAME_HEIGHT (-> webcam-options :video :height)))

    (ou/.read webcam-capture webcam-buffer)
    (oc/cvt-color! webcam-buffer oc/COLOR_RGB2GRAY)
    (.release webcam-capture)
    webcam-buffer))

```

I'm pretty confident I've got this part working. (I've managed to put the whole webcam feed into a JPanel/window after a couple of days of fiddling with it and that code is pretty similar). It returns what I expect

`#object[org.opencv.core.Mat 0x7aff8afb "Mat [ 240*320*CV_8UC1, isCont=true, isSubmat=false, nativeObj=0x7f290c4c5690, dataAddr=0x7f290c4fdb40 ]"]`

Next I try to grab one value with 

`(.get (webcam-bufferedimage-still) 10 10)`

and I get out something that looks like `#object["[D" 0x5781b74c "[D@5781b74c"]`

I also tried 'at' as well as wrapping the return in an (int .. ) and playing with different argument lengths... I can't seem to get the value. I also did a：

`(.dump (webcam-bufferedimage-still))`

and that does display the values in a long string - so i know the values are inside there somewhere :)

According to [this](https://stackoverflow.com/questions/3318671/clojures-gen-class-and-double-arrays) it seems like this might be a namespace/loading issue?

The top of my file/namespace reads

```
(ns simple-plot.core
  (:require
   [thi.ng.geom.core :as g]
   [thi.ng.geom.viz.core :as viz]
   [thi.ng.geom.svg.core :as svgthing]
   [thi.ng.math.core :as m :refer [PI TWO_PI]]
   [opencv3.core :as oc]
   [opencv3.video :as ov]
   [opencv3.utils :as ou]
   [seesaw.core :as sc]
   [seesaw.icon :as si]
   [seesaw.dev :as sd]
   [analemma.xml :as ax]
   [tikkba.core :as tc]
   [tikkba.dom :as td]
   [tikkba.swing :as ts]))
```

Let me know if you're seeing anything similar or if I'm missing something obvious here. Or maybe there is a smarter way to turn the image matrix into a clojure map/vector?

**Comment by hellonico** [comment]
Suppose you have a 10x10 mat, each pixel being made of a scalar of three values. (three integers)
```
(def test-mat (new-mat 10 10 CV_8UC3))
```

We'll set a default value [100 200 100] (something green in RGB landscape) on all the pixels of the mat

```
(set-to test-mat (new-scalar 100 200 100))
```

Getting the value of a single pixel is done by calling the *.get* on the mat:

```
(def pixel (.get test-mat 1 1))
```

You get an array of values, here three:

```
(first pixel)
(second pixel)
(nth pixel 2)

; 100.0
; 200.0
; 100.0
```

**Comment by geokon-gh** [comment]
Thanks again for the help. I thought I was avoiding that issue by using one channel but what you're saying works

I'm looking at `Mat.java` again now and I see I was looking at the wrong function overload for Mat. This is the one we're using here:
`
    public double[] get(int row, int col) {
/* ... */
}
`
So the .get is returning a Java array, and those can be treated as a Clojure sequence according to here: https://clojure.org/reference/sequences
and that's why `first` and `second` work here

Though I still wonder why I can't  prompt for `pixel`'s type here.. Maybe I'd need to include Java arrays somewhere in my namespacing

**Comment by hellonico** [comment]
Here are a few more methods that you may find useful:

```clojure
; this let you know if pixel is an array or not 
(.isArray (class pixel))
; true

; this let you know the type of element of the array
(.getComponentType (class pixel))
; double

; this prints the small array in a readable format
(clojure.pprint/pprint pixel)
; [100.0, 200.0, 100.0]
```

**Comment by hellonico** [comment]
btw, doing pixel by pixel is great to learn :) 
But there are also opencv specific java methods to achieve this.

I've collected before them in the example below:
https://github.com/hellonico/opencv-fun/blob/master/test/opencv3/histo.clj

**Comment by geokon-gh** [comment]
Haha, yeah, no you're absolutely right. I'm just sorta playing around and making a simple toy example to get familiar with Clojure and the libraries (origami/seesaw/thi.ng). I wasn't quite sure how to massage the data elements to put it into `calc-hist` so I decided to quickly roll my own. I'll put up a repo in a bit and link you

**Comment by geokon-gh** [comment]
I finally got something nice working...

OpenCV/Origami + JavaFX/fn-fx + Thi.ng-geom

https://geokon-gh.github.io/buubletea/
https://github.com/geokon-gh/buubletea

That took significantly longer than I expected.. but I learned a lot in the process :)

**Comment by hellonico** [comment]
Hi George ! 
Great ! 
But I cannot get it to run ... 

Exception in thread "JavaFX Application Thread" java.lang.ClassCastException: javafx.stage.Stage cannot be cast to javafx.scene.Node
	at fn_fx.fx_tree_search$find_child_by_id.invokeStatic(fx_tree_search.clj:23)
	at fn_fx.fx_tree_search$find_child_by_id.invoke(fx_tree_search.clj:22)
	at fn_fx.fx_tree_search$find_nearest_by_id.invokeStatic(fx_tree_search.clj:37)
	at fn_fx.fx_tree_search$find_nearest_by_id.invoke(fx_tree_search.clj:34)
	at fn_fx.render_core$gather_event_data$fn__885.invoke(render_core.clj:279)

Do you have a different java version or should I do something else ?

**Comment by geokon-gh** [comment]
Thanks for trying it out :) I get those errors too but the app launches for me nonetheless

I started with an example project provided by fn-fx and it strangely had those errors from the get-go. I'll try to see if I can figure out what's causing them

**Comment by geokon-gh** [comment]
Okay! Fixed. There was some minor issue in the example `fn-fx` project from which I'd started. Everything should work now

There is a small issue that won't affect the program running , but the histograms aren't being bottom aligned. I've been banging my head trying to figure out how to fix it, but I haven't quite narrowed it down. They work like 50% of the time.. haha. I'm strill trying to wrap my head around [geom-viz](https://github.com/thi-ng/geom/blob/master/geom-viz/src/index.org)

Other than that everything is hooked up. Hope it works this time. Sorry about the bug

**Comment by hellonico** [comment]
Conversation continued in:
https://github.com/geokon-gh/buubletea/issues/1

Closing this for now!
