### ISSUE TITLE
Maven Respository Down: https://repository.hellonico.info/repository/hellonico/

### ISSUE THREAD

**Issue by narendraj9** [hellonico/origami#60]
The repository endpoint returns: `504 Gateway Time-out nginx/1.6.2`
Please take a look. :)

**Comment by hellonico** [comment]
will do later on today!.

**Comment by narendraj9** [comment]
Thank you very much for the prompt response :)

**Comment by hellonico** [comment]
it's up again ! Please confirm it works for you.

**Comment by narendraj9** [comment]
It's working now. Is there any way I can help to keep the repository up? :) What was the problem? Thanks for putting the effort :)

**Comment by hellonico** [comment]
Do you have a clojars account ?

**Comment by hellonico** [comment]
recently, problem is always a server disk full error ... 
This is a private repository that I am hosting and I don't have super advanced monitoring.

**Comment by narendraj9** [comment]
> Do you have a clojars account ?

Yes, I have a clojars account.

> recently, problem is always a server disk full error ...

Is it because new artifacts are getting uploaded to the repository or other things like logs?
