### ISSUE TITLE
SSL Cert issue

### ISSUE THREAD

**Issue by crofty** [hellonico/origami#62]
I think there may be a problem with the SSL certs.  I'm getting some errors when trying to install.  Visiting https://repository.hellonico.info/repository/hellonico/ in a browser is displaying an error as the cert expired 4 days ago:

> This server could not prove that it is repository.hellonico.info; its security certificate expired 4 days ago. This may be caused by a misconfiguration or an attacker intercepting your connection.

**Comment by hellonico** [comment]
just noticing this now (´；ω；｀)
will fix it today 
really sorry

**Comment by hellonico** [comment]
So sorry  it took so long.
The SSL certificates have been updated.

**Comment by hellonico** [comment]
Also updated nexus to:
 Nexus Repository 3.30.1

**Comment by hellonico** [comment]
let me know if I can help you getting up to speed.
