### ISSUE TITLE
in docker.

### ISSUE THREAD

**Issue by etherny** [hellonico/origami#9]
Hello i try to use the lib in docker container and i receive this error :

```
OpenJDK 64-Bit Server VM warning: You have loaded library /tmp/nativelib-loader_341152294144260927/libopencv_java400.so which might have disabled stack guard. The VM will try to fix the stack guard now.
It's highly recommended that you fix the library with 'execstack -c <libfile>', or link it with '-z noexecstack'.
```

Here the docker file

```
FROM openjdk:jdk
RUN apt update && apt install -y libcglib-java
COPY indexation.jar indexation.jar
```
Command line : 

`docker run backend java -jar indexation.jar`

PS: the indexation.jar works ouside of docker

**Comment by blackholegalaxy** [comment]
to add more information on that, we tried two thing to get similar thing done with no success:

 - find the .so file then use `execstack` on it but since the `/tmp/xxx/libopencv_java400.so file is made accessible at build time and not run time, then in the docker running the jar we cannot reach this .so file.

**Comment by hellonico** [comment]
Hi there,

not sure how you are creating your fat jar, there is a sample Dockerfile in the sibling test project:
https://github.com/hellonico/origami_samples_libc2_19/

It uses a more compatible native jar, so with leiningen:
[opencv/opencv-native-ubuntu16-noffmpeg "4.0.0-beta"]

or maven:

<dependency>
<groupId>opencv</groupId>
<artifactId>opencv-native-ubuntu16-noffmpeg</artifactId>
<version>4.0.0-beta</version>
</dependency>

**Comment by hellonico** [comment]
I just deployed a new version of origami (4.0.0-beta7) making that opencv-native version the default.

I took the opportunity to deprecate the [above project,](https://github.com/hellonico/origami_samples_libc2_19/) so you can just have a look at the [samples project](https://github.com/hellonico/origami_samples).

Some docker instructions are here:
https://github.com/hellonico/origami_samples#docker

**Comment by hellonico** [comment]
by the way, I'd be super happy if there were any examples you could share ;)

**Comment by etherny** [comment]
Hello, i m using embaded jar, not lein command in docker image.

Here my project file : 
```clojure
(defproject indexation "0.1.0-SNAPSHOT"
  :description "FIXME: write description"
  :url "http://example.com/FIXME"
  :license {:name "Eclipse Public License"
            :url  "http://www.eclipse.org/legal/epl-v10.html"}
  :repositories [["vendredi" "https://repository.hellonico.info/repository/hellonico/"]]
  :dependencies [[org.clojure/clojure "1.9.0"]
                 [origami "4.0.0-beta7"]
                 [opencv/opencv-native-libc_2_19 "4.0.0-beta"]
                 [org.clojure/clojure "1.9.0"]]
  :main indexation.image-processing)

```

Here the code

```clojure
(ns indexation.image-processing
  (:gen-class)
  (:require [opencv4.core :refer [imread resize! new-size imwrite]]))

(defn resize-keep-ratio! [mat new-width]
  (let [size (.size mat)
        width (.width size)
        height (.height size)
        ratio (/ width height)
        new-height (/ new-width ratio)]
    (println "Image from" width "x" height "to" new-width "x" new-height)
    (resize! mat (new-size new-width new-height))))
;
(defn -main [& args]
  (time (-> "resources/photo.jpg"
            (imread)
            (resize-keep-ratio! 300)
            (imwrite "resources/output.png"))))
```
Dockerfile

```docker
FROM openjdk:jdk

COPY indexation-0.1.0-SNAPSHOT-standalone.jar indexation.jar
COPY resources resources
```
Docker image building : 
- Uberjar in lein project folder (indexation.jar)
- Copy jar in dockerfile folder.
- copy resources used by the test
- docker build --no-cache -t local/indexation .
- docker run --rm local/indexation java -jar indexation.jar

**Comment by hellonico** [comment]
Thanks for the feedback.

Sorry my explanation was not clear.
You don' t need to use this anymore:
 [opencv/opencv-native-libc_2_19 "4.0.0-beta"]
just remove it from your project.clj file.

I have created a repository with two docker files:
https://github.com/hellonico/origami-indexation

Hope it works for you.

**Comment by etherny** [comment]
You are very responsive, i will try.

**Comment by etherny** [comment]
It's working, thank you for your job !
